language: groovy

jdk:
  - oraclejdk7
  - oraclejdk8
  - openjdk7

before_script:
  - cd ..
  - git clone https://github.com/moqui/moqui.git moqui
  - cd moqui/runtime
  - git clone https://github.com/moqui/mantle.git mantle
  - cd ..

script:
  - gradle cleanAll load
  - gradle check
  - gradle runtime/mantle/mantle-usl:test --info
